libvirt_group: '{{ ''libvirt'' if ansible_os_family == ''RedHat'' else ''libvirtd'' }}'
cfielder_dirs:
  - .config/i3
  - .config/nvim
  - .config/terminator
  - .config/alacritty
  - .fonts
  - go
  - go/src
  - go/bin
  - go/pkg
  - .local/share/konsole
