---
all_pkgs:
  - bash
  - bash-completion
  - tmux
  - htop
  - nmap
  - pavucontrol
  - redshift
  - git
  - qbittorrent
  - curl
  - docker-compose
  - xclip
  - python3
  - python3-pip
  - golang
  - neovim

fedora_pkgs:
  - vim-enhanced
  - chromium
  - docker
  - "@Virtualization"
  - libguestfs-tools-c
  - python2
  - python2-pip
  - python2-devel
  - python3-devel
  - python2-libselinux
  - python3-libselinux
  - google-chrome-stable

ubuntu_pkgs:
  - vim
  - chromium-browser
  - docker.io
  - python
  - python-pip
  - python-dev
  - python3-dev
  - qemu-kvm
  - libvirt-clients
  - libvirt-daemon-system
  - virtinst
  - virt-viewer
  - virt-manager
  - ttf-mscorefonts-installer
  - "libgnutls30:i386"
  - "libldap-2.4-2:i386"
  - "libgpg-error0:i386"
  - "libsqlite3-0:i386"
  - libvulkan1
  - "libvulkan1:i386"
  - steam
  - winetricks
  - lutris
  - ukuu
  - signal-desktop
  - quassel-client
  - openssh-server
  - code
  - kubectl
  - libssl-dev
  - libssh2-1-dev
  - libgit2-dev

apt_keys:
  - "http://download.opensuse.org/repositories/home:/strycore/xUbuntu_{{ansible_distribution_version}}/Release.key"
  - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
  - "https://packages.microsoft.com/keys/microsoft.asc"
  - "https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Ubuntu_{{ansible_distribution_version}}_standard/Release.key"
  - "https://updates.signal.org/desktop/apt/keys.asc"

ppas:
  - "ppa:graphics-drivers/ppa"
  - "ppa:teejee2008/ppa"

remote_debs:
  - "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  - "https://github.com/jwilm/alacritty/releases/download/v0.2.6/Alacritty-v0.2.6_amd64.deb"

apt_repos:
  - repo: >-
      deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Ubuntu_{{ansible_distribution_version}}_standard ./
    filename: winehq
  - repo: >-
      deb
      http://download.opensuse.org/repositories/home:/strycore/xUbuntu_{{ansible_distribution_version}}/
      ./
    filename: lutris
  - repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    filename: kubernetes
  - repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    filename: vscode
  - repo: "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
    filename: signal-desktop

go_pkgs:
  - vault
  - consul
  - packer
  - terraform
