---
- name: Install pkgs
  hosts: localhost
  become: True
  tasks:

    - name: Enable chrome repo
      yum_repository:
        name: google-chrome
        description: Google Chrome Repository
        baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
        gpgcheck: 1
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub
        enabled: True
      when: ansible_distribution == 'Fedora'

    - name: Enable fedy
      yum_repository:
        name: fedy
        description: Fedy Repository
        baseurl: https://dl.folkswithhats.org/fedora/$releasever/
        gpgcheck: 0
        enabled: True
      when: ansible_distribution == 'Fedora'

    - name: Add RPM Fusion Free
      yum_repository:
        name: rpmfusion-free
        description: RPM Fusion for Fedora $releasever - Free
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
        enabled: True
        gpgcheck: True

    - name: Add RPM Fusion Free Updates
      yum_repository:
        name: rpmfusion-free-updates
        description: RPM Fusion for Fedora $releasever - Free - Updates
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
        enabled: True
        gpgcheck: True

    - name: Add RPM Fusion Non-free
      yum_repository:
        name: rpmfusion-nonfree
        description: RPM Fusion for Fedora $releasever - Nonfree
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
        enabled: True
        gpgcheck: True

    - name: Add RPM Fusion Non-free Updates
      yum_repository:
        name: rpmfusion-nonfree-updates
        description: RPM Fusion for Fedora $releasever - Nonfree - Updates
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch
        enabled: True
        gpgcheck: True

    - name: update repo
      dnf: name="*" state=latest
      when: ansible_distribution == 'Fedora'
      register: repo_data

    - debug: var=repo_data
      when: repo_data.changed

    - name: install pkgs
      dnf:
        name:
          - bash
          - bash-completion
          - tmux
          - htop
          - nmap
          - pavucontrol
          - redshift
          - git
          - qbittorrent
          - curl
          - docker-compose
          - weechat
          - vim-enhanced
          - chromium
          - docker
          - "@Virtualization"
          - python2
          - python2-pip
          - python2-devel
          - python3
          - python3-pip
          - python3-devel
          - python2-libselinux
          - python3-libselinux
          - golang
          - neovim
          - google-chrome-stable
        state: present
      when: ansible_distribution == 'Fedora'
      register: installed_packages

    - debug: var=installed_packages
      when: installed_packages.changed
