---
- name: Install pkgs
  hosts: localhost
  become: True
  tasks:
    - name: update repo
      dnf: name="*" state=latest
      when: ansible_distribution == 'Fedora'
      register: result

    - debug: var=result
      when: result.changed

    - name: install pkgs
      dnf:
        name:
          - bash
          - bash-completion
          - tmux
          - htop
          - nmap
          - mpv
          - pavucontrol
          - redshift
          - git
          - qbittorrent
          - curl
          - docker-compose
          - weechat
          - vim-enhanced
          - chromium
          - docker
          - "@Virtualization"
          - python2
          - python2-pip
          - python2-devel
          - python3
          - python3-pip
          - python3-devel
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Enable chrome repo
      yum_repository:
        name: google-chrome
        description: Google Chrome Repository
        baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
        gpgcheck: 1
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub
        enabled: True
      when: ansible_distribution == 'Fedora'

    - name: Enable fedy
      yum_repository:
        name: fedy
        description: Fedy Repository
        baseurl: https://dl.folkswithhats.org/fedora/$releasever/
        gpgcheck: 0
        enabled: True
      when: ansible_distribution == 'Fedora'
