- name: Fedora package tasks
  block:
    - name: Enable chrome repo
      yum_repository:
        name: google-chrome
        description: Google Chrome Repository
        baseurl: 'http://dl.google.com/linux/chrome/rpm/stable/$basearch'
        gpgcheck: 1
        gpgkey: 'https://dl.google.com/linux/linux_signing_key.pub'
        enabled: true
    - name: Enable fedy
      yum_repository:
        name: fedy
        description: Fedy Repository
        baseurl: 'https://dl.folkswithhats.org/fedora/$releasever/'
        gpgcheck: 0
        enabled: true
    - name: Enable VSCode repo
      yum_repository:
        name: code
        description: Visual Studio Code
        baseurl: 'https://packages.microsoft.com/yumrepos/vscode'
        enabled: true
        gpgcheck: true
        gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
    - name: Setup RPM Fusion Repos
      dnf:
        name:
          - >-
            https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{
            ansible_distribution_version }}.noarch.rpm
          - >-
            https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{
            ansible_distribution_version }}.noarch.rpm
    - name: Enable Kubernetes
      yum_repository:
        name: kubernetes
        file: kubernetes
        description: Kubernetes
        baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey:
          - 'https://packages.cloud.google.com/yum/doc/yum-key.gpg'
          - 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
    - name: update repo
      dnf: name="*" state=latest
      register: repo_data
    - debug: var=repo_data
      when: repo_data.changed
    - name: install pkgs
      dnf:
        name:
          - bash
          - bash-completion
          - tmux
          - htop
          - nmap
          - pavucontrol
          - redshift
          - git
          - qbittorrent
          - curl
          - docker-compose
          - weechat
          - vim-enhanced
          - xclip
          - chromium
          - docker
          - '@Virtualization'
          - libguestfs-tools-c
          - python2
          - python2-pip
          - python2-devel
          - python3
          - python3-pip
          - python3-devel
          - python2-libselinux
          - python3-libselinux
          - golang
          - neovim
          - google-chrome-stable
        state: present
      register: installed_packages
    - debug: var=installed_packages
      when: installed_packages.changed
  when: ansible_distribution == 'Fedora'
- name: Ubuntu package tasks
  block:
    - name: Install wine key
      apt_key:
        url: 'https://dl.winehq.org/wine-builds/Release.key'
        state: present
    - name: Install lutris key
      apt_key:
        url: 'http://download.opensuse.org/repositories/home:/strycore/xUbuntu_{{ansible_distribution_version}}/Release.key'
        state: present
    - name: Install nvidia driver repository
      apt_repository:
        repo: 'ppa:graphics-drivers/ppa'
    - name: Install ukuu repository
      apt_repository:
        repo: 'ppa:teejee2008/ppa'
    - name: Install wine repository
      apt_repository:
        repo: >-
          deb https://dl.winehq.org/wine-builds/ubuntu/
          {{ansible_distribution_release}} main
        filename: /etc/apt/sources.list.d/winehq
        state: present
    - name: Install lutris repository
      apt_repository:
        repo: >-
          deb
          http://download.opensuse.org/repositories/home:/strycore/xUbuntu_{{ansible_distribution_version}}/
          ./
        filename: /etc/apt/sources.list.d/lutris
        state: present
    - name: Install vscode repository
      apt_repository:
        repo: >-
          deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
        filename: /etc/apt/sources.list.d/lutris
        state: present
    - name: Update apt repository
      apt:
        update_cache: yes
        cache_valid_time: 86400
    - name: Install apt packages
      apt:
        name: '{{item}}'
        state: present
      with_items:
        - bash
        - bash-completion
        - tmux
        - htop
        - nmap
        - pavucontrol
        - redshift
        - git
        - qbittorrent
        - curl
        - docker-compose
        - weechat
        - vim
        - xclip
        - chromium-browser
        - docker.io
        - python
        - python-pip
        - python-dev
        - python3
        - python3-pip
        - python3-dev
        - golang
        - neovim
        - qemu-kvm
        - libvirt-bin
        - virtinst
        - virt-viewer
        - ttf-mscorefonts-installer
        - 'libgnutls30:i386'
        - 'libldap-2.4-2:i386'
        - 'libgpg-error0:i386'
        - 'libsqlite3-0:i386'
        - libvulkan1
        - 'libvulkan1:i386'
        - nvidia-driver-396
        - steam
        - winetricks
        - lutris
        - ukuu
    - name: Install wine and recommended packages
      apt:
        name: '{{item}}'
        state: present
        install_recommends: true
      with_items:
        - wine-staging
    - name: Upgrade packages
      apt:
        upgrade: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
  when: ansible_distribution == 'Ubuntu'
- name: Install Minikube
  get_url:
    url: >-
      https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    checksum: 'sha256:3c84872ffa5ddbce472062fb548f9b3a25af72587d35243e12f18d86aaa6a085'
    mode: 509
- name: Install docker-machine
  get_url:
    url: >-
      https://github.com/docker/machine/releases/download/v0.15.0/docker-machine-Linux-x86_64
    dest: /usr/local/bin/docker-machine
    checksum: 'sha256:44c5c62db13b6eb6a9d3e276c1181401c78327ff6303570936ba2cf5d137b7b5'
    mode: 509
- name: Install docker-machine KVM driver
  get_url:
    url: >-
      https://github.com/kubernetes/minikube/releases/download/v0.28.0/docker-machine-driver-kvm2
    dest: /usr/local/bin/docker-machine-driver-kvm2
    mode: 509
