- name: Fedora package tasks
  block:
    - name: Enable chrome repo
      yum_repository:
        name: google-chrome
        description: Google Chrome Repository
        baseurl: "http://dl.google.com/linux/chrome/rpm/stable/$basearch"
        gpgcheck: 1
        gpgkey: "https://dl.google.com/linux/linux_signing_key.pub"
        enabled: true

    - name: Enable VSCode repo
      yum_repository:
        name: code
        description: Visual Studio Code
        baseurl: "https://packages.microsoft.com/yumrepos/vscode"
        enabled: true
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"

    - name: Setup RPM Fusion Repos
      dnf:
        name:
          - >-
            https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{
            ansible_distribution_version}}.noarch.rpm
          - >-
            https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{
            ansible_distribution_version}}.noarch.rpm

    - name: Enable Kubernetes
      yum_repository:
        name: kubernetes
        file: kubernetes
        description: Kubernetes
        baseurl: >-
          "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey:
          - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
          - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"

    - name: update repo
      dnf:
        name: "*"
        state: latest
      register: repo_data

    - debug:
        var: repo_data
      when: repo_data.changed

    - name: install pkgs
      dnf:
        name: "{{all_pkgs}} + {{fedora_pkgs}}"
        state: present
      register: installed_packages

    - debug:
        var: installed_packages
      when: installed_packages.changed

  when: ansible_distribution == 'Fedora'

- name: Ubuntu package tasks
  block:
    - name: Install apt keys
      apt_key:
        url: "{{ item }}"
        state: present
      loop: "{{ apt_keys }}"

    - name: Install ppas
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop: "{{ ppas }}"

    - name: Install apt repos
      apt_repository:
        repo: "{{ item.repo }}"
        filename: "{{ item.filename }}"
        state: present
      loop: "{{ apt_repos }}"
      tags:
        - wine

    - name: Update apt repository
      apt:
        update_cache: true
        cache_valid_time: 86400
      tags:
        - nox

    - name: Install apt packages
      apt:
        name: "{{all_pkgs}} + {{ubuntu_pkgs}}"
        state: present

    - name: Install remote deb packages
      apt:
        deb: "{{ item }}"
      loop: "{{ remote_debs }}"

    - name: Install wine and recommended packages
      apt:
        name: winehq-staging
        state: present
        install_recommends: true

    - name: Upgrade packages
      apt:
        upgrade: true
      register: installed_packages
      tags:
        - nox

    - debug:
        var: installed_packages
      when: installed_packages.changed

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: true
      tags:
        - nox

  when: ansible_distribution == 'Ubuntu'

- name: Install go packages
  command: "go get -u github.com/hashicorp/{{item}}"
  loop: "{{ go_pkgs }}"
  become: cfielder
  tags:
    - go
    - nox

- name: Install Minikube
  get_url:
    url: >-
      https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/
    mode: 509
  async: 60
  poll: 0

- name: Install docker-machine
  get_url:
    url: >-
      https://github.com/docker/machine/releases/download/v0.15.0/docker-machine-Linux-x86_64
    dest: /usr/local/bin/
    mode: 509
  async: 60
  poll: 0

- name: Install docker-machine KVM driver
  get_url:
    url: >-
      https://github.com/kubernetes/minikube/releases/download/v0.29.0/docker-machine-driver-kvm2
    dest: /usr/local/bin/
    mode: 509
  async: 60
  poll: 0

- name: Install docker-machine bash completion scripts
  get_url:
    url: >-
      https://raw.githubusercontent.com/docker/machine/master/contrib/completion/bash/docker-machine.bash
    dest: /etc/bash_completion.d/docker-machine.bash
    mode: 292
  async: 60
  poll: 0
