- name: Fedora package tasks
  block:
    - name: Enable chrome repo
      yum_repository:
        name: google-chrome
        description: Google Chrome Repository
        baseurl: 'http://dl.google.com/linux/chrome/rpm/stable/$basearch'
        gpgcheck: 1
        gpgkey: 'https://dl.google.com/linux/linux_signing_key.pub'
        enabled: true
    - name: Enable fedy
      yum_repository:
        name: fedy
        description: Fedy Repository
        baseurl: 'https://dl.folkswithhats.org/fedora/$releasever/'
        gpgcheck: 0
        enabled: true
    - name: Enable VSCode repo
      yum_repository:
        name: code
        description: Visual Studio Code
        baseurl: 'https://packages.microsoft.com/yumrepos/vscode'
        enabled: true
        gpgcheck: true
        gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
    - name: Setup RPM Fusion Repos
      dnf:
        name:
          - >-
            https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{
            ansible_distribution_version}}.noarch.rpm
          - >-
            https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{
            ansible_distribution_version}}.noarch.rpm
    - name: Enable Kubernetes
      yum_repository:
        name: kubernetes
        file: kubernetes
        description: Kubernetes
        baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey:
          - 'https://packages.cloud.google.com/yum/doc/yum-key.gpg'
          - 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
    - name: update repo
      dnf:
        name: '*'
        state: latest
      register: repo_data
    - debug:
        var: repo_data
      when: repo_data.changed
    - name: install pkgs
      dnf:
        name: '{{all_pkgs}} + {{fedora_pkgs}}'
        state: present
      register: installed_packages
    - debug:
        var: installed_packages
      when: installed_packages.changed
  when: ansible_distribution == 'Fedora'
- name: Ubuntu package tasks
  block:
    - name: Install apt keys
      apt_key:
        url: '{{ item }}'
        state: present
      with_items: '{{ apt_keys }}'
    - name: Install ppas
      apt_repository:
        repo: '{{ item }}'
        state: present
      with_items: '{{ ppas }}'
    - name: Install apt repos
      apt_repository:
        repo: '{{ item.repo }}'
        filename: '{{ item.filename }}'
        state: present
      with_items: '{{ apt_repos }}'
    - name: Update apt repository
      apt:
        update_cache: yes
        cache_valid_time: 86400
    - name: Install apt packages
      apt:
        name: '{{item}}'
        state: present
      with_items: '{{all_pkgs}} + {{ubuntu_pkgs}}'
    - name: Install wine and recommended packages
      apt:
        name: '{{item}}'
        state: present
        install_recommends: true
      with_items:
        - wine-staging
    - name: Upgrade packages
      apt:
        upgrade: yes
      register: installed_packages
    - debug:
        var: installed_packages
      when: installed_packages.changed
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
  when: ansible_distribution == 'Ubuntu'
- name: Install Minikube
  get_url:
    url: >-
      https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/
    mode: 509
- name: Install docker-machine
  get_url:
    url: >-
      https://github.com/docker/machine/releases/download/v0.15.0/docker-machine-Linux-x86_64
    dest: /usr/local/bin/
    mode: 509
- name: Install docker-machine KVM driver
  get_url:
    url: >-
      https://github.com/kubernetes/minikube/releases/download/v0.29.0/docker-machine-driver-kvm2
    dest: /usr/local/bin/
    mode: 509
