---
# vars file for system
sysctl_settings:
  - name: vm.swappiness
    value: 0
  - name: fs.inotify.max_user_watches
    value: 524288
  - name: net.core.default_qdisc
    value: fq
  - name: net.ipv4.tcp_congestion_control
    value: bbr
