---
- name: Install docker-machine bash completion scripts
  get_url:
    url: https://raw.githubusercontent.com/docker/machine/master/contrib/completion/bash/docker-machine.bash
    dest: /etc/bash_completion.d/docker-machine.bash
    mode: 0444
  become: True

- name: Create /home/images
  file:
    path: /home/images
    mode: 0770
    owner: root
    group: libvirtd
    state: directory
  become: True
  when: ansible_distribution == 'Ubuntu'

- name: Create /home/images
  file:
    path: /home/images
    mode: 0770
    owner: root
    group: libvirt
    state: directory
  become: True
  when: ansible_distribution == 'Fedora'

- name: Add groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - cfielder
    - docker
  become: True

- block:
  - name: Add cfielder
    user:
      name: cfielder
      comment: Craig James Fielder
      shell: /bin/bash
      group: cfielder
      groups:
        - libvirt
        - docker
      append: yes
      uid: 1000
  become: True
  when: ansible_distribution == 'Fedora'

- block:
  - name: Add cfielder
    user:
      name: cfielder
      comment: Craig James Fielder
      shell: /bin/bash
      group: cfielder
      groups:
        - libvirtd
        - docker
      append: yes
      uid: 1000
  - name: Add libvirtd group
    group:
      name: libvirtd
      state: present
  become: True
  when: ansible_distribution == 'Ubuntu'

- name: Make dirs
  file:
    path: /home/cfielder/{{ item }}
    owner: cfielder
    group: cfielder
    mode: 0755
    state: directory
  with_items:
    - .config/i3
    - .config/nvim
    - .config/terminator
    - .config/alacritty
    - .fonts
    - .weechat
    - go
    - go/src
    - go/bin
    - go/pkg
    - .local/share/konsole

- name: Install files
  copy:
    src: "{{ item.key }}"
    dest: "/home/cfielder/{{ item.value }}"
    owner: cfielder
    group: cfielder
  with_dict:
    # filename: location
    alacritty: .config/alacritty/alacritty.yml
    bashrc: .bashrc
    i3: .config/i3/config
    profile: .profile
    redshift: .config/redshift.conf
    tmux: .tmux.conf
    vimrc: .vimrc
    weechat: .weechat/weechat.conf
    dracula_colorscheme: .local/share/konsole/Dracula.colorscheme
    konsole_profile: .local/share/konsole/dracula.profile

- name: Create alacritty desktop shortcut
  copy:
    src: alacritty.desktop
    dest: /usr/share/applications/Alacritty.desktop
  become: True

- name: Make nvim config symlink
  file:
    src: /home/cfielder/.vimrc
    dest: /home/cfielder/.config/nvim/init.vim
    owner: cfielder
    group: cfielder
    mode: 0644
    state: link

- name: Test for alacritty
  stat: path=/home/cfielder/.cargo/bin/alacritty
  register: alacritty_present

- name: Make global alacritty symlink
  file:
    src: /home/cfielder/.cargo/bin/alacritty
    dest: /usr/local/bin/alacritty
    mode: 0755
    state: link
  when: alacritty_present.stat.exists == True
  become: True
