- name: Install docker-machine bash completion scripts
  get_url:
    url: >-
      https://raw.githubusercontent.com/docker/machine/master/contrib/completion/bash/docker-machine.bash
    dest: /etc/bash_completion.d/docker-machine.bash
    mode: 0444
  become: true
  tags:
    - nox

- name: Add groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - cfielder
    - "{{ libvirt_group }}"
  become: true
  tags:
    - nox

- name: Create /home/images
  file:
    path: /home/images
    mode: 0770
    owner: root
    group: "{{ libvirt_group }}"
    state: directory
  become: true

- block:
    - name: Add cfielder
      user:
        name: cfielder
        comment: Craig James Fielder
        shell: /bin/bash
        group: cfielder
        groups:
          - "{{ libvirt_group }}"
        append: true
        uid: 1000
  become: true
  tags:
    - nox

- name: Make dirs
  file:
    path: "/home/cfielder/{{ item }}"
    owner: cfielder
    group: cfielder
    mode: 0760
    state: directory
  with_items: "{{ cfielder_dirs }}"
  tags:
    - nox

- name: Install files
  copy:
    src: "{{ item.key }}"
    dest: "/home/cfielder/{{ item.value }}"
    owner: cfielder
    group: cfielder
  with_dict:
    alacritty: .config/alacritty/alacritty.yml
    bashrc: .bashrc
    i3: .config/i3/config
    profile: .profile
    redshift: .config/redshift.conf
    tmux: .tmux.conf
    vimrc: .vimrc
    dracula_colorscheme: .local/share/konsole/Dracula.colorscheme
    konsole_profile: .local/share/konsole/dracula.profile
  tags:
    - nox

- name: Create alacritty desktop shortcut
  copy:
    src: alacritty.desktop
    dest: /usr/share/applications/Alacritty.desktop
  become: true

- name: Make nvim config symlink
  file:
    src: /home/cfielder/.vimrc
    dest: /home/cfielder/.config/nvim/init.vim
    owner: cfielder
    group: cfielder
    mode: 0600
    state: link
  tags:
    - nox

- name: Test for alacritty
  stat: path=/home/cfielder/.cargo/bin/alacritty
  register: alacritty_present

- name: Make global alacritty symlink
  file:
    src: /home/cfielder/.cargo/bin/alacritty
    dest: /usr/local/bin/alacritty
    mode: 0755
    state: link
  when: alacritty_present.stat.exists == True
  become: true
