pipeline {
    agent { 
        node { label 'desktop' } 
    }
    stages {

        stage('init') {
            checkout scm
        }

        stage('build') {
            ansiblePlaybook(
                playbook: 'main.yml',
                inventory: 'hosts.yml',
                limit: 'local',
                colorized: true)
        }
    }
}
