pipeline {
    agent {
        node {
            label 'desktop'
        }
    }
    stages {
        stage('build') {
            steps {
                ansiblePlaybook(
                    playbook: 'playbooks/main.yml',
                    inventory: 'playbooks/hosts.yml',
                    limit: 'local'
                )
            }
        }
    }
}
