pipeline {
    agent { 
        node { label 'desktop' } 
    }
    stages {
        stage('build') {
            steps {
                    ansiblePlaybook(
                        playbook: 'main.yml',
                        inventory: 'hosts.yml',
                        colorized: true)
            }
        }
    }
}
