- hosts: all
  roles:
    - role: system
      become: true
      tags: system
    - role: pkgs
      become: true
      tags: pkgs
    - role: cfielder
      tags: cfielder
      become: true
    - role: vscode
      tags: vscode
