---
- hosts: local
  tasks:
    - import_role:
        name: system
      become: true
      tags: system
    - import_role:
        name: pkgs
      become: true
      tags: pkgs
    - import_role:
        name: cfielder
      tags: cfielder
