---
- name: Set sysctls
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: True
  with_items: "{{ sysctl_settings }}"
  tags:
    - nox

- name: Set timezone to EST
  timezone:
    name: America/New_York
  tags:
    - nox

- name: Setup journald.conf file
  copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 644
  tags:
    - nox
