---

- name: Set sysctls
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: True
  with_items: "{{ sysctl_settings }}"
  tags:
    - nox

- name: Setup journald.conf file
  copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - nox

- name: Setup sudoers file
  lineinfile:
    path: /etc/sudoers
    state: present
    line: 'Defaults !tty_tickets'
    validate: 'visudo -cf %s'
