---
- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: 0
    state: present

- name: Set timezone to EST
  timezone:
    name: America/New_York

- name: Setup journald.conf file
  copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 644
