---
- name: Set timezone to UTC
  timezone:
    name: UTC

- name: Setup journald.conf file
  copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 644
